stages:
  - build_docker

#--- Variables
variables:
  DOCKER_URL: $CI_REGISTRY_IMAGE
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_DRIVER: overlay2
#------

#--- Build rules
.build_rules:
  rules:
    - if: $CI_COMMIT_TAG =~ /^v/
      variables:
        IMAGE_TAG: $CI_COMMIT_TAG
        IS_RELEASE: 1
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: on_success
    - when: never

#--- Start build docker...
Build docker:
  stage: build_docker
  tags:
    - logiq
  extends:
    - .build_rules
  services:
    - docker:dind
  image: docker:latest
  before_script:
    - docker login -u $DOCKER_HUB_LOGIN -p $DOCKER_HUB_PASS #Login to public Docker Hub
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build --cache-from $DOCKER_URL:latest --pull -t $DOCKER_URL:$IMAGE_TAG -f Dockerfile .
    - docker push $DOCKER_URL:$IMAGE_TAG
    - '[ ! -z "$IS_RELEASE" ] && docker tag $DOCKER_URL:$IMAGE_TAG $DOCKER_URL:latest'
    - '[ ! -z "$IS_RELEASE" ] && docker push $DOCKER_URL:latest'
    - docker rmi $DOCKER_URL:$IMAGE_TAG
#------
